---
- hosts: vagrant
  vars:
    # Configure for your project
    project_alias: "myproject"

    # You can normally leave these alone
    vagrant_user: "vagrant"
    site_root: "/home/{{ vagrant_user }}/{{ project_alias }}"
    venv_dir: "virtualenvs"
    venv_root: ~/{{ venv_dir }}
    workon: WORKON_HOME={{ venv_root }}
    project_venv: /home/$USER/{{ venv_dir }}/{{ project_alias }}
    requirements: "{{ site_root }}/requirements.txt"
  user: vagrant  # default "vagrant"
  tasks:
    - name: Update apt cache
      sudo: yes
      apt: update_cache=yes cache_valid_time=86400

    - name: Install git
      sudo: yes
      apt: pkg=git-core state=present

    - name: Install screen
      sudo: yes
      apt: pkg=screen state=present

    - name: Install vim for one-off edits (or swap in your own :))
      sudo: yes
      apt: pkg=vim state=present

    - name: Install Python build essentials
      sudo: yes
      apt: pkg=python-dev state=present

    - name: Install Python packaging tools (1/2)
      sudo: yes
      apt: pkg=python-pip state=present

    - name: Install Python packaging tools (2/2)
      sudo: yes
      apt: pkg=python-virtualenv state=present

    - name: Installed to manage repos from which you install software from #TODO may not *need* this
      sudo: yes
      apt: pkg=python-software-properties state=present

    - name: Install JPEG libraries for PIL
      sudo: yes
      apt: pkg=libjpeg-dev state=present

    - name: Install PostgreSQL (1/3)
      sudo: yes
      apt: pkg=libpq-dev state=present

    - name: PostgreSQL (2/3)
      sudo: yes
      apt: pkg=postgresql state=present

    - name: PostgreSQL (3/3)
      sudo: yes
      apt: pkg=postgresql-client state=present

    - name: Install and configure virtualenvwrapper 
      sudo: yes
      pip: name=virtualenvwrapper 

    - name: Ensure virtualenvwrapper dir is present
      shell: mkdir -p {{ venv_root }}

    - name: Source virtualenvwrapper boostrap script
      shell: executable=/bin/bash export {{ workon }} && source `which virtualenvwrapper.sh`

    - name: Creates virtualenv
      shell: executable=/bin/bash virtualenv {{ project_venv }}

    - name: Install project packages
      shell: executable=/bin/bash source {{ project_venv}}/bin/activate && pip install -r {{ requirements }}

    - name: Saves virtualenvwrapper path
      shell: echo "\nexport {{ workon }}" >> ~/.bashrc

    - name: Source virtualenvwrapper on login
      shell: echo "\nsource \`which virtualenvwrapper.sh\`" >> ~/.bashrc

    - name: Activate project virtualenv on login
      shell: echo "\nworkon {{ project_alias }}" >> ~/.bashrc
